/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetsSlugRouteImport } from './routes/projets.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsSlugRoute = ProjetsSlugRouteImport.update({
  id: '/projets/$slug',
  path: '/projets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projets/$slug': typeof ProjetsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projets/$slug': typeof ProjetsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projets/$slug': typeof ProjetsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confidentialite'
    | '/mentions-legales'
    | '/sitemap.xml'
    | '/projets/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confidentialite'
    | '/mentions-legales'
    | '/sitemap.xml'
    | '/projets/$slug'
  id:
    | '__root__'
    | '/'
    | '/confidentialite'
    | '/mentions-legales'
    | '/sitemap.xml'
    | '/projets/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjetsSlugRoute: typeof ProjetsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/$slug': {
      id: '/projets/$slug'
      path: '/projets/$slug'
      fullPath: '/projets/$slug'
      preLoaderRoute: typeof ProjetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjetsSlugRoute: ProjetsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
